### ISSUE TITLE
Fix CI/CD build

### ISSUE THREAD

**Issue by pjattke** [MarbleHE/AST-Optimizer#1]
The GitHub Actions build does currently not work. On the local dev machine (macOS) it works, however, without any issues. Probably, the issues are related to implementation-specific differences between Apple's Clang and gcc.

I would recommend debugging the issues using a local Linux (e.g., Ubuntu) installation with gcc. Maybe it's worth investigating the exact gcc version that is used in the CI/CD build.

**Comment by AlexanderViand** [comment]
As of 80f6e487cc63f976ab0d173dcb6a446021f71212 both ubuntu gcc and mac os clang github actions build correctly
